// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OfferteTool;

#nullable disable

namespace OfferteTool.Migrations
{
    [DbContext(typeof(OfferteContext))]
    partial class OfferteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OfferteTool.Offerte", b =>
                {
                    b.Property<string>("Offertenummer")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RelatieEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Offertenummer");

                    b.ToTable("Offertes");
                });
#pragma warning restore 612, 618
        }
    }
}
